/* autogenerated by Processing revision 1276 on 2021-09-30 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class random_contador extends PApplet {

 float x, y, r, g, b;
 String[] listaFrutas = {"melón", "naranja", "kiwi", "plátano", "manzana"};
 PFont font;
 int dim, contador;
 float angulo;
 
 
 public void setup(){
  /* size commented out by preprocessor */;
  background(0);
  font = loadFont("SansSerif-48.vlw");
  frameRate(10);
  contador = 0;
  
}

 public void draw(){
 
  x = random(-50, 350);
  y = random(-10, 410);
  r = random(256);
  g = random(256);
  b = random(256);
  dim = PApplet.parseInt(random(12, 50));
  angulo = radians(random(-30, 30));
  
  fill(r, g, b, 10);
  rect(0,0, width, height);
  
  fill(r, g, b);
  textFont(font, dim);
  //text(listaFrutas[int(random(listaFrutas.length))], x, y);
  
  pushMatrix();
  
  translate(x, y);
  rotate(angulo);
  text(listaFrutas[contador % 5], 0, 0);
  contador++;
  
  popMatrix();
  
}


  public void settings() { size(400, 400); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "random_contador" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
